-- ==========================================
-- 1. BRONZE LAYER (RAW STAGING)
-- ==========================================
-- Purpose: To store data exactly as it comes from the CSV.
DROP TABLE bronze_sales_raw;
CREATE TABLE bronze_sales_raw (
    sale_id    VARCHAR2(50),
    sale_date  VARCHAR2(50),
    amount     VARCHAR2(50),
    region     VARCHAR2(50)
);

-- ==========================================
-- 2. SILVER LAYER (SCD TYPE 2 & CLEANED)
-- ==========================================
-- Purpose: The "Source of Truth" with history tracking.
DROP TABLE silver_sales_clean;
CREATE TABLE silver_sales_clean (
    sales_sk    NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sale_id     NUMBER,
    sale_date   DATE,
    amount      NUMBER(10,2),
    region      VARCHAR2(50),
    start_date  DATE,
    end_date    DATE,
    is_current  CHAR(1),
    upd_dt      DATE DEFAULT SYSDATE
);

-- Indexing for Performance (Gold Layer Optimization)
CREATE INDEX idx_silver_sales_perf ON silver_sales_clean (sale_id, is_current, region);

-- ==========================================
-- 3. GOLD LAYER (ANALYTICAL VIEWS)
-- ==========================================
-- Purpose: Aggregated data for business dashboards.
CREATE OR REPLACE VIEW gold_regional_performance AS
SELECT 
    region,
    TO_CHAR(sale_date, 'YYYY-MM') as sale_month,
    SUM(amount) as total_revenue,
    COUNT(*) as transaction_count
FROM silver_sales_clean
WHERE is_current = 'Y'
GROUP BY region, TO_CHAR(sale_date, 'YYYY-MM');