-- ==========================================
-- 1. BRONZE LAYER (RAW STAGING)
-- ==========================================
-- Purpose: To store data exactly as it comes from the CSV.
DROP TABLE bronze_sales_raw;
CREATE TABLE bronze_sales_raw (
    sale_id    VARCHAR2(50),
    sale_date  VARCHAR2(50),
    amount     VARCHAR2(50),
    region     VARCHAR2(50)
);

-- ==========================================
-- 2. SILVER LAYER (SCD TYPE 2 & CLEANED)
-- ==========================================
-- Purpose: The "Source of Truth" with history tracking.
DROP TABLE silver_sales_clean;
CREATE TABLE silver_sales_clean (
    sales_sk    NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sale_id     NUMBER,
    sale_date   DATE,
    amount      NUMBER(10,2),
    region      VARCHAR2(50),
    start_date  DATE,
    end_date    DATE,
    is_current  CHAR(1),
    upd_dt      DATE DEFAULT SYSDATE
);

-- Indexing for Performance (Gold Layer Optimization)
CREATE INDEX idx_silver_sales_perf ON silver_sales_clean (sale_id, is_current, region);

-- ==========================================
-- 3. GOLD LAYER (ANALYTICAL VIEWS)
-- ==========================================
-- Purpose: Aggregated data for business dashboards.
CREATE OR REPLACE VIEW gold_regional_performance AS
SELECT 
    region,
    TO_CHAR(sale_date, 'YYYY-MM') as sale_month,
    SUM(amount) as total_revenue,
    COUNT(*) as transaction_count
FROM silver_sales_clean
WHERE is_current = 'Y'
GROUP BY region, TO_CHAR(sale_date, 'YYYY-MM');

-- ==========================================
-- 4. SILVER QUARANTINE LAYER (ANALYTICAL VIEWS) 
-- ==========================================
-- Purpose: for moving bad rows into the silver_sales_quarantine for manual inspection 
DROP TABLE silver_sales_quarantine;
CREATE TABLE silver_sales_quarantine (
    quarantine_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sale_id       VARCHAR2(50),
    raw_data      CLOB,
    error_reason  VARCHAR2(200),
    rejected_at   TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    resolved_flag CHAR(1) DEFAULT 'N'
);

-- ==========================================
-- 5. pipeline_logs (ANALYTICAL VIEWS) 
-- ==========================================
-- Purpose: making everyting log for easier maintance rather than checking data 
DROP TABLE pipeline_logs;
CREATE   TABLE pipeline_logs (
    log_id      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_name    VARCHAR2(100),
    status      VARCHAR2(20),  
    start_ts    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    end_ts      TIMESTAMP,
    error_msg   CLOB
);
